const SUPABASE_URL="https://kfrshaagrcggcjalsjdu.supabase.co";const SUPABASE_KEY="sb_publishable_mKftrB-itebmeA-bdtt6dw_Q3QnxH0_";const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let me=null,role=null,leads=[];const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const today=()=>new Date().toISOString().slice(0,10);
$("loginBtn").onclick=async()=>{const {data,error}=await db.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error){$("loginMsg").textContent=error.message;return}await init()};
$("logoutBtn").onclick=()=>db.auth.signOut().then(()=>location.reload());
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.hidden=true);$("view-"+b.dataset.view).hidden=false;if(b.dataset.view==="leads")renderLeads();if(b.dataset.view==="calls")renderCalls();if(b.dataset.view==="rank")renderRank()});
async function init(){const {data:{user}}=await db.auth.getUser();me=user;if(!me)return;const p=await db.from("user_profiles").select("full_name,role,is_active").eq("id",me.id).maybeSingle();role=p.data?.role||"sales";$("userInfo").textContent=(p.data?.full_name||me.email)+" • "+role;$("login").hidden=true;$("main").hidden=false;await loadLeads();await renderDashboard()}
async function loadLeads(){let q=db.from("leads").select("*").order("updated_at",{ascending:false}).limit(500);if(role!=="admin"&&role!=="branch_manager")q=q.eq("user_id",me.id);const r=await q;leads=r.data||[]}
async function stats(){const start=today()+"T00:00:00";let q=db.from("call_logs").select("id,contact_type,outcome,created_at,assigned_user_id",{count:"exact",head:false}).gte("created_at",start);if(role!=="admin"&&role!=="branch_manager")q=q.eq("assigned_user_id",me.id);const r=await q;return r.data||[]}
async function renderDashboard(){const calls=await stats();const count=t=>calls.filter(x=>x.contact_type===t).length;const target={expired:25,old:15,social_media:15,invitation:10,tour:10,follow_up:15};const total=calls.length;const connected=calls.filter(x=>!["no_answer","wrong_number"].includes(x.outcome)).length;const appointments=calls.filter(x=>x.outcome==="appointment"||x.outcome==="tour").length;const joined=calls.filter(x=>x.outcome==="joined").length;let ref=await db.from("sales_referrals").select("id",{count:"exact",head:true}).eq("referrer_sales_user_id",me.id);$("view-dashboard").innerHTML=`<div class="grid"><div class="stat">Calls today<b>${total}/90</b><div class="progress"><i style="width:${Math.min(total/90*100,100)}%"></i></div></div><div class="stat">Connected<b>${connected}</b></div><div class="stat">Appointments/Tours<b>${appointments}</b></div><div class="stat">Joined<b>${joined}</b></div><div class="stat">Rank-In<b>${ref.count||0}</b></div></div><div class="panel"><h2>Daily Call Target</h2>${Object.entries(target).map(([k,v])=>`<div class="row"><span>${label(k)}</span><span>${count(k)} / ${v}</span></div>`).join("")}</div><div class="panel"><h2>Workflow</h2><p class="small">Calls → Connected → Appointment → Tour → Joined → Rank-In</p></div>`}
function label(k){return({expired:"Expired Data",old:"Old Data",social_media:"Social Media",invitation:"Invitation",tour:"Tour",follow_up:"Follow-up"})[k]||k}
function renderLeads(){const html=leads.map(l=>`<div class="row"><div><b>${esc(l.name)}</b><div class="small">${esc(l.phone)} • <span class="tag">${esc(l.source||"unknown")}</span></div></div><button onclick="openLead('${l.id}')">Call / Update</button></div>`).join("");$("view-leads").innerHTML=`<div class="panel"><h2>Leads (${leads.length})</h2>${html||"<p>لا توجد Leads مخصصة لك.</p>"}</div>`}
async function openLead(id){const l=leads.find(x=>x.id===id);const sr=await db.from("sales_scripts").select("title,script").eq("source",l.source||"old").maybeSingle();$("modal").hidden=false;$("modal").innerHTML=`<div class="card"><h2>${esc(l.name)}</h2><p>${esc(l.phone)}</p><p class="small">Script: ${esc(sr.data?.title||"Sales")}</p><div class="panel"><p>${esc(sr.data?.script||"اتكلم مع العميل بشكل طبيعي واسأله عن هدفه ثم اقترح زيارة.")}</p></div><select id="outcome"><option value="connected">Connected</option><option value="no_answer">No Answer</option><option value="appointment">Appointment</option><option value="tour">Tour</option><option value="joined">Joined</option><option value="call_back">Call Back</option><option value="not_interested">Not Interested</option><option value="wrong_number">Wrong Number</option></select><br><br><textarea id="notes" placeholder="ملاحظات المكالمة"></textarea><br><br><button onclick="saveCall('${l.id}')">حفظ المكالمة</button> <button class="ghost" onclick="closeModal()">إلغاء</button></div>`}
function closeModal(){$("modal").hidden=true}
async function saveCall(leadId){const l=leads.find(x=>x.id===leadId),outcome=$("outcome").value,notes=$("notes").value;const r=await db.from("call_logs").insert({lead_id:leadId,agent_id:me.id,assigned_user_id:me.id,contact_name:l.name,contact_phone:l.phone,contact_type:l.source||"old",direction:"outbound",outcome,notes,created_at:new Date().toISOString()});if(r.error){alert(r.error.message);return}await db.from("leads").update({last_contacted_at:new Date().toISOString(),next_action:outcome==="call_back"?"follow_up":outcome,notes}).eq("id",leadId);closeModal();await loadLeads();await renderDashboard()}
async function renderCalls(){const calls=await stats();$("view-calls").innerHTML=`<div class="panel"><h2>Today's Calls</h2>${calls.map(c=>`<div class="row"><span>${esc(c.contact_type)}</span><span class="tag">${esc(c.outcome||"—")}</span></div>`).join("")||"<p>لا توجد مكالمات اليوم.</p>"}</div>`}
async function renderRank(){const r=await db.from("sales_referrals").select("id,status,rank_points,created_at").eq("referrer_sales_user_id",me.id).order("created_at",{ascending:false});$("view-rank").innerHTML=`<div class="panel"><h2>Rank-In</h2><p>كل Referral جديد يتسجل هنا ويتحول إلى Joined عند الاشتراك.</p>${(r.data||[]).map(x=>`<div class="row"><span>${esc(x.status)}</span><b>+${x.rank_points} point</b></div>`).join("")||"<p>لا يوجد Rank-In حتى الآن.</p>"}</div>`}
db.auth.getSession().then(async({data})=>{if(data.session)await init()});